### PR TITLE
implemented tracing for stan channels

### PR DESCRIPTION
**Pull request by astelmashenko**
Fixes #

Eventing-natss did not have tracing implemented. After configuring [eventing tracing](https://knative.dev/docs/eventing/accessing-traces/#configuring-tracing) trace did not look right way. Eventing-natss dispatcher did not pass traceparent via stan channel.

Let's consider a simple scenario (analogue to [distributed-tracing](https://knative.dev/blog/articles/distributed-tracing/))
heartbit-srv -> broker -> filter -> event-display-srv
Tracing was stored as two separate tracing:
Screenshot from 2022-06-03 15-31-50
Screenshot from 2022-06-03 15-31-24

## Proposed Changes
Enable tracing config and implement passing traceparent and tracestate w3c headers via stan channels.

After this PR is applied tracing is looking like this:
Screenshot from 2022-06-15 18-06-13

- 🐛 Fix bug

```release-note
Enabled tracing for NatssChannel objects.
```

P.S.: this may helpful for jetstream implementation as well

### CODE REVIEW

**Comment by lionelvillard** [comment]
It looks good, thanks!

@astelmashenko can you please fix the failing checks (Code Style, Unit tests and Verify)?

**Comment by astelmashenko** [comment]
> It looks good, thanks!
> 
> @astelmashenko can you please fix the failing checks (Code Style, Unit tests and Verify)?

sure, will do

**Comment by astelmashenko** [comment]
@lionelvillard , I've signed EasyCLA and received confirmation email, but it did not change EasyCLA check. I can not understand why, asked support. Should it be re-scanned from somewhere?

**Comment by astelmashenko** [comment]
I closed that PR, because I made commits with wrong git global configs, please review now this one https://github.com/knative-sandbox/eventing-natss/pull/342

**Pull request closed without merging**
