### PR TITLE
[Release-0.19] Cp 63,65, 67

### LINKED ISSUE #62: Channel has two reconcilers updating it's status. That can lead to badness.
**Describe the bug**
While debugging an issue with natss channel, I noticed that the controller reconciler updates the status of the channel to indicate the channel resources have been created. But, the dispatcher reconciler also updates the status. I think this is a bug, similar to what we saw in IMC, some of the details of the issue are reported here:
https://github.com/knative/eventing/issues/3686

I think what should be done is to patch the status from the dispatcher instead of using a genreconciler style ReconcileKind method.
Something like this:
https://github.com/knative/eventing/blob/master/pkg/reconciler/inmemorychannel/dispatcher/inmemorychannel.go#L94 

 **Expected behavior**
A single reconciler only does a Status update.

 **To Reproduce**
Steps to reproduce the behavior.

 **Knative release version**

 **Additional context**
Add any other context about the problem here such as proposed priority

### PR DESCRIPTION
**Pull request by vaikas**
Fixes #62 #64 #86 

## Proposed Changes

- Cherry pick #63 #65 #67 to release 0.19
-
-

**Release Note**

```release-note
- 🐛 Fix bug #62 #64 #86

```

**Docs**

### CODE REVIEW

**Comment by vaikas** [comment]
@googlebot I consent.

**Comment by vaikas** [comment]
googlebot I fixed it.

**Comment by vaikas** [comment]
@googlebot I fixed it.

**Comment by vaikas** [comment]
@googlebot I fixed it.

**Review by n3wscott — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
