### PR TITLE
Update deps with DeadLetterChannel removal

### LINKED ISSUE #388: Get rid of the removed DeadLetterChannel in ChannelableStatus
**Problem**
This PR https://github.com/knative/eventing/pull/6722 removes `DeadLetterChannel` in ChannelableStatus

We will have to remove it from the following places
- https://github.com/knative-sandbox/eventing-natss/blob/e1340217a7afb996d6264d4f97bb1b2a10dfa3ed/pkg/reconciler/dispatcher/jetstream/nats_jetstreaming_schannel.go#L291
- https://github.com/knative-sandbox/eventing-natss/blob/e1340217a7afb996d6264d4f97bb1b2a10dfa3ed/pkg/reconciler/dispatcher/natss/natsschannel.go#L291

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)**
Which persona is this feature for?

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.

**Time Estimate (optional):**
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

### PR DESCRIPTION
**Pull request by evankanderson**
Fixes #388
Fixes #389

(Sorry @Vishal-Chdhry, I was in a hurry, I give you full credit for #389)

## Proposed Changes

- Remove obsolete DeadLetterChannel field
- Run `update_deps.sh --upgrade --release v1.10 --module-release v1.10`

**Release Note**

```release-note
* Updates knative.dev component dependencies from September 2022 to v1.10
```

### CODE REVIEW

**Review by Vishal-Chdhry — CHANGES_REQUESTED** [review]
Should this be removed as well? 
https://github.com/knative-sandbox/eventing-natss/blob/e1340217a7afb996d6264d4f97bb1b2a10dfa3ed/pkg/apis/messaging/v1alpha1/nats_jetstream_types.go#L75

https://github.com/knative-sandbox/eventing-natss/blob/a5e426dbfc5fc21581ef8c0a3254e93f2595860f/pkg/apis/messaging/v1beta1/natss_channel_types.go#L75

https://github.com/knative-sandbox/eventing-natss/blob/a5e426dbfc5fc21581ef8c0a3254e93f2595860f/config/jetstream/302-jsm-channel.yaml#L341-L359

**Comment by astelmashenko** [comment]
@evankanderson, looks good to me. The only thing is the changes specified by @Vishal-Chdhry , but those are minor.
Should we mark it as lgtm or wait for minor changes commit?

**Comment by evankanderson** [comment]
Let me get the docs today, and then you can lgtm

**Comment by evankanderson** [comment]
Okay, I removed the references; I don't understand how `302-jsm-channel.yaml` got generated, so I'm not sure it won't get added back at some point.

**Comment by astelmashenko** [comment]
Does it mean we will see eventing-natss 1.10 soon?

**Pull request merged**
