### PR TITLE
Update nats streaming image version to 0.22.0

### LINKED ISSUE #198: Update nats streaming  image version to 0.22.0
**Problem**
Update nats streaming image before we deprecate it. Update from `0.11.0` to `0.22.0`

And the nats streaming image version list is [here](https://hub.docker.com/_/nats-streaming?tab=tags&page=1&ordering=last_updated)

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)**

**Exit Criteria**

**Time Estimate (optional):**
How many developer-days do you think this may take to resolve?

0.5

**Additional context (optional)**
Add any other context about the feature request here.

### PR DESCRIPTION
**Pull request by zhaojizhuang**
Fixes #198
Update nats streaming image version from 0.11.0 to 0.22.0 befor we deprecate it.

## Proposed Changes

- udpate go mod
- upate nats streaming image version to 0.22.0

**Release Note**

```release-note
Update nats streaming image version from 0.11.0 to 0.22.0 
```

**Docs**

### CODE REVIEW

**Comment by vaikas** [comment]
Looks like you need to run update scripts?
```
knative-sandbox/eventing-natss is out of date. Please run hack/update-codegen.sh
```

**Comment by zhaojizhuang** [comment]
> Looks like you need to run update scripts?
> 
> ```
> knative-sandbox/eventing-natss is out of date. Please run hack/update-codegen.sh
> ```

Done! @vaikas

**Comment by zhaojizhuang** [comment]
ping @vaikas

**Pull request merged**
