### PR TITLE
Fix removed Eventing test images

### PR DESCRIPTION
**Pull request by dsimansk**
Fixes #

## Proposed Changes

- Fix removed Eventing test images
- Bump Go version to be on pair with the rest

The same issue as with eventing-rabbitmq. There's ref to older test image, that doesn't exist in the latest Eventing repo. Therefore auto update actions are failing to bump everythig.

/cc @knative-sandbox/eventing-natss-approvers

### CODE REVIEW

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve
/hold for tests

**Comment by pierDipi** [comment]
```

fatal: ambiguous argument 'vendor/knative.dev/eventing/test/test_images/heartbeats/main.go': unknown revision or path not in the working tree.
```
https://github.com/knative-sandbox/eventing-natss/actions/runs/4806453127/jobs/8553991154?pr=399

**Comment by dsimansk** [comment]
@pierDipi updated

**Review by pierDipi — APPROVED** [review]
/unhold
/lgtm

**Pull request merged**
