### PR TITLE
fixed tracing propagation for jsm channel

### PR DESCRIPTION
**Pull request by astelmashenko**
The same changes as in PR https://github.com/knative-sandbox/eventing-natss/pull/342 applied for JetStream

### CODE REVIEW

**Comment by dprotaso** [comment]
I don't have the context here to approve - I'll assign the other eventing WG lead (@pierDipi)

/unassign @dprotaso 
/assign @pierDipi

**Comment by astelmashenko** [comment]
@pierDipi , @lionelvillard ,
I re-based on latest code, added additional nil checks and tracing full test coverage. All green and ready for review.
Thanks

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
