### PR TITLE
ported jsm implementation PR #267

### PR DESCRIPTION
**Pull request by astelmashenko**
Porting mainstream changes https://github.com/knative-sandbox/eventing-natss/pull/267

### CODE REVIEW

**Comment by astelmashenko** [comment]
@zhaojizhuang , I know that there is codeql error, but the error is from vendor dependency. It is transient dependency of knative.dev/eventing 0.30.0, and I'm working on release-1.3.

**Comment by lionelvillard** [comment]
@zhaojizhuang @dan-j do you have some cycles to review this PR?

**Pull request merged**
