### PR TITLE
Changes from mainstream jetstream development

### PR DESCRIPTION
**Pull request by astelmashenko**
Changes from PR https://github.com/knative-sandbox/eventing-natss/pull/267 and https://github.com/knative-sandbox/eventing-natss/pull/380

should fix https://github.com/knative-sandbox/eventing-natss/issues/334

### CODE REVIEW

**Comment by astelmashenko** [comment]
@upodroid , this is the PR with failing styles/gofmt

**Comment by upodroid** [comment]
/override codecov/patch
/override codecov/project
/override "style / Auto-format and Check (gofmt)"
/override "style / Auto-format and Check (goimports)"
/override "verify / Verify Deps and Codegen"

**Comment by astelmashenko** [comment]
@rhuss , there are few failed steps, but those are codestyle of generated sources.

**Comment by pierDipi** [comment]
Pinging folks that were commenting on the referenced PRs:
/cc @Foxman13 @zadus @dan-j

**Comment by pierDipi** [comment]
Is there any reason you're not working primarly on the main branch?

**Pull request closed without merging**
